VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Class1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public Enum LGEContextual
Record_Type = 1
Enrollment_ID
Premise_ID
WO_Number
System_Name
Not_Applicable
System_Type
Fuel_Source
Square_Footage
Perimeter_Footage
System_Size
Size_Unit_of_Measure
System_Age
Quantity
Efficiency_Rating
Efficiency_Rating_Type
Percent_of_space_heated_or_cooled
Frequency_of_system_use
Total_units_used
Insulation_exist_indicator
Insulation_Type
R_Value
Location
Length
height
Depth
Percent_of_Load
Current_temperature_setting
Energy_Factor
Condition_of_flex_duct
Average_cooling_temperature
Average_heating_temperature
Day_setback_indicator
Evening_setback_indicator
Night_setback_indicator
Heating_day_temperature_setting
Heating_evening_temperature_setting
Heating_night_temperature_setting
Cooling_day_temperature_setting
Cooling_evening_temperature_setting
Cooling_night_temperature_setting
AC_load_control_present_indicator
Condition_of_window_or_door
Total_window_surface_area
Window_UV_coated_indicator
Number_of_window_glazings
Weekly_operating_hours
Existing_bulb_wattage
Vent_required_indicator
Access_Type
Basement_air_conditioned_indicator
Rim_joist_recommended_indicator
Defrost_Type
System_make_manufacturer
Metered_Usage

End Enum

